# Ansible
ansible_user: remote-user

# Users
server_remote_user: remote-user

# Network
router_ip_address: 192.168.1.1

# Server
homelab_ip_address: 192.168.1.10

# Dropbear / Remote crypto unlock
dropbear_server_ip: 192.168.1.11
dropbear_gateway: "{{ router_ip_address }}"
dropbear_netmask: 255.255.255.0
dropbear_hostname: homelab

# SSL - Self signed certificates
use_self_signed_certificates: false

certificate_directory: /etc/ssl/homelab
private_key_filename: private.key
certificate_filename: self-signed.crt

certificate_signing_request_filename: home-arpa.csr
root_ca_private_key_filename: root-ca.key
root_ca_certificate_filename: root-ca.crt

# Groups
service_group: services
media_group: media

# Directories

media_directory: /srv/media
media_download_directory: /srv/media/downloads

### Services ###

# Pihole
pihole_dns_servers: 9.9.9.9;149.112.112.112

# Traefik
traefik_admin_user: admin

# Portainer
portainer_admin_user: admin
