- hosts: homelab
  vars_files:
    - group_vars/secrets.yml

  roles:
    - role: system
      tags:
        - system
    - role: dropbear
      tags:
        - dropbear
    - role: ssl
      tags:
        - ssl
    - role: traefik
      tags:
        - traefik
    - role: pihole
      tags:
        - pihole
    - role: portainer
      tags:
        - portainer
    - role: nextcloud
      tags:
        - nextcloud
    - role: gitea
      tags:
        - gitea
    - role: homeassistant
      tags:
        - homeassistant
    - role: jellyfin
      tags:
        - jellyfin
    - role: qbit
      tags:
        - qbit
    - role: servarr
      tags:
        - servarr
    - role: cleanup
      tags:
        - cleanup