- name: Gather package facts
  package_facts:
    manager: apt
  no_log: true

# Install required packages
- block:
    - name: Ensure APT is updated
      apt:
        update_cache: yes

    - name: Install apache2-utils for htpasswd
      apt:
        name: apache2-utils
        state: latest

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
        state: present

    - name: Update APT cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install latest Docker Engine
      apt:
        name: docker-ce
        state: latest

    - name: Install latest docker compose (CLI plugin)
      apt:
        name: docker-compose-plugin
        state: latest

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

  become: true

# Users and groups
- block:
  - name: Create group for service users
    group:
      name: "{{ service_group }}"
      state: present

  - name: Create group for media services
    group:
      name: "{{ media_group }}"
      state: present

  - name: Set ownership of media folder
    file:
      path: "{{ media_directory }}"
      owner: root
      group: "{{ media_group }}"
      recurse: yes

  - name: Create media subfolders
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: "{{ media_group }}"
    loop:
      - "{{ media_download_directory }}"
      - "{{ media_directory }}/movies"
      - "{{ media_directory }}/series"
      - "{{ media_directory }}/music"

  - name: Set permissions on media folder
    file:
      path: "{{ media_directory }}"
      mode: "2775"
      recurse: yes

  - name: Add remote user to services-group
    user:
      name: "{{ server_remote_user }}"
      groups:
        - "{{ service_group }}"
        - "{{ media_group }}"
      append: yes
      state: present

  - name: Create authorized keys for remote user
    copy:
      dest: /home/{{ server_remote_user }}/.ssh/authorized_keys
      content: |
        {% for key in authorized_keys %}
        {{ key }}
        {% endfor %}
      owner: remote-user
      group: remote-user
      mode: '0600'

  become: true